"""empty message

Revision ID: 946afacb577b
Revises: 116664d4491e
Create Date: 2026-05-14 17:46:27.169749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946afacb577b'
down_revision = '116664d4491e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
